CREATE OR REPLACE FUNCTION func_generate_id()
RETURNS BIGINT
AS
$func$
BEGIN
	RETURN(
		SELECT
		FLOOR(EXTRACT('epoch' FROM (CURRENT_TIMESTAMP - TIMESTAMP '01-01-1970 00:00:00')))
		|| LPAD(CAST(MOD(CAST(FLOOR(EXTRACT(MICROSECONDS FROM CURRENT_TIMESTAMP)) AS INTEGER), 1000) AS VARCHAR), 3, '0')
		|| FLOOR(random() * (9-2 + 1) + 2)
		|| FLOOR(random() * (10-20 + 1) + 20)
	);
END
$func$
LANGUAGE plpgsql;